name: todo_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  serverpod_flutter: ^1.2.2
  serverpod_auth_email_flutter: ^1.2.2
  serverpod_auth_shared_flutter: ^1.2.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  todo_client:
    path: ../todo_client
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  hard_analyser: ^1.7.0

flutter:
  uses-material-design: true
